VTA-292: (BE) Update VTA dependencies
dvsa/cvs-tsk-update-status pull request #28
Opened 2022-01-28 10:48 UTC by Daniel-Searle

## Update VTA dependencies

Upgrade the npm packages having high vulnerabilities
[link to ticket number](https://jira.dvsacloud.uk/browse/VTA-292)

## Checklist

- [x] Branch is rebased against the latest develop
- [x] PR title includes the JIRA ticket number
- [ ] Squashed commits contain the JIRA ticket number
- [ ] Link to the PR added to the repo

2022-02-01 08:14 UTC, cb-cs approved these changes

2022-02-01 08:16 UTC, cb-cs requested changes
@Daniel-Searle - can you add the --prod flag to the audit script in package.json please.

2022-02-07 08:59 UTC, cb-cs approved these changes

2022-02-07 10:21 UTC, m-coslett approved these changes

2022-02-24 15:40 UTC, merged